### ISSUE TITLE
ITD Allelic fraction

### ISSUE THREAD

**Issue by roysomak4** [tommyau/itdseek#2]
Hello,
Is it possible to incorporate calculation of allelic fraction of ITD or at least total coverage across the region in which ITD is detected?
Thanks!

**Comment by tommyau** [comment]
Thank you for your suggestion and I will try to implement this as a new feature. If you are referring to data from TruSight myeloid panel, do you think average sequencing depth across the 3 overlapping amplicons would be a suitable denominator to calculate allelic fraction?

**Comment by roysomak4** [comment]
Yes, I am referring to the TruSight myeloid panel. I agree that the coverage across three overlapping amplicons will be variable and therefore the denominator will not be accurate. Alternatively, will it be possible to compute the denominator only for the locus harboring the ITD instead across all three amplicons for every case?
Regardless of how the denominator is computed, we are looking to use that information for a rough estimate of the allelic burden. It will be a helpful feature.  
Thanks!

**Comment by tommyau** [comment]
ITD allele fraction estimation is implemented in the latest commit f643c79. Could you give it a try and share any feedback?

**Comment by roysomak4** [comment]
Sure. Thanks!
