### ISSUE TITLE
VCF Contains large chunk of sequence

### ISSUE THREAD

**Issue by xrho** [tommyau/itdseek#3]
After running itdseek.sh, the output VCF file contains a large chunk of sequence with both capital and lower case letters that continue for many lines. Following the chunk of sequence, are more appropriately organized data that is in VCF format. The problem is that there are ITDs in the large chunk of sequence that are only detectable by sorting through the entire chunk.

**Comment by tommyau** [comment]
Thanks for trying ITDseek and reporting this. In rare occasion, some datasets have weird soft-clipping pattern so that ITDseek thinks there is a very huge internal tandem duplication. Could you share the VCF output to confirm this?

**Comment by xrho** [comment]
The file is quite large (~50 MB). Could I email it to you?

**Comment by tommyau** [comment]
Please try to compress it to under 10MB and send to chau@hksh.com

**Comment by xrho** [comment]
I am going to use the Yale File Transfer Service. It will send you a link that you can use to obtain the file. It is saved as a .txt.zip file to minimize file size. The file name is 17_475_IX013.itdseek.txt.zip.

**Comment by xrho** [comment]
Please let me know if you were able to receive the file.

**Comment by tommyau** [comment]
Indeed you hit the rare occasion that I mentioned. The ITD candidates are over 20Mb in length (please refer to the VAF INFO field LEN=) and I prefer to regard them as false positive artifact.
I am thinking of implementing maximum ITD length (for example 10,000bp) so that such false positive can be filtered. For backward compatibility, such length limit may be implemented as an opt-in feature. What do you think? Thanks.

**Comment by xrho** [comment]
I think that would be a great feature! Thanks for all of your help!

**Comment by tommyau** [comment]
After balancing backward compatibility and reasonably good default parameters, I prefer a good default approach to exclude exceedingly long candidates (>5000bp for both clipping and insertion modes). In other words, this maximum length is now a built-in (opt-out) feature.
Please refer to the latest commit b76459a2f1af8cd83f4ec1d4ad2caefa84821a2d and have a try.
