### ISSUE TITLE
Test my own samples

### ISSUE THREAD

**Issue by ydy1127** [tommyau/itdseek#7]
Hello, I have installed and tested the samples you provided on the server.
If I use my own samples to run this tool, do you have specific requirements for the file format of SAM/BAM?

**Comment by tommyau** [comment]
ITDseek expects a bam file generated by BWA-MEM with -M option (as described in README at https://github.com/tommyau/itdseek).

**Comment by ydy1127** [comment]
Hi！
&nbsp; &nbsp;&nbsp;Thank you for your answer.
&nbsp; &nbsp;May I ask whether the ITDseek is only suitable for amplicon&nbsp;sequencing data, and whether it is suitable for hkuozybridization&nbsp;sequencing data?
&nbsp; &nbsp; &nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Tommy Au"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月30日(星期一) 中午1:44
收件人:&nbsp;"tommyau/itdseek"<itdseek@noreply.github.com&gt;;
抄送:&nbsp;"我是ydy"<1614999088@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [tommyau/itdseek] Test my own samples (#7)




ITDseek expects a bam file generated by BWA-MEM with -M option (as described in README at https://github.com/tommyau/itdseek).

**Comment by ydy1127** [comment]
Hi！
&nbsp; &nbsp;
&nbsp; &nbsp;&nbsp;I would also like to ask what principle the insertion mode mentioned in the source code（ line 83-108 in itdseek.pl） is based on to identify ITDs.


&nbsp; &nbsp;&nbsp;Looking forward to your reply. Thank you！
&nbsp; &nbsp;&nbsp;


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"我是ydy"<1614999088@qq.com&gt;;
发送时间:&nbsp;2019年12月31日(星期二) 上午10:20
收件人:&nbsp;"tommyau/itdseek"<reply@reply.github.com&gt;;

主题:&nbsp;回复： [tommyau/itdseek] Test my own samples (#7)



Hi！
&nbsp; &nbsp; Thank you for your answer.
&nbsp; &nbsp;May I ask whether the ITDseek is only suitable for amplicon sequencing data, and whether it is suitable for hkuozybridization sequencing data?
&nbsp; &nbsp; &nbsp;




------------------ 原始邮件 ------------------
发件人:&nbsp;"Tommy Au"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月30日(星期一) 中午1:44
收件人:&nbsp;"tommyau/itdseek"<itdseek@noreply.github.com&gt;;
抄送:&nbsp;"我是ydy"<1614999088@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [tommyau/itdseek] Test my own samples (#7)




ITDseek expects a bam file generated by BWA-MEM with -M option (as described in README at https://github.com/tommyau/itdseek).

**Comment by tommyau** [comment]
> Hi！ &nbsp; &nbsp;&nbsp;Thank you for your answer. &nbsp; &nbsp;May I ask whether the ITDseek is only suitable for amplicon&nbsp;sequencing data, and whether it is suitable for hkuozybridization&nbsp;sequencing data? &nbsp; &nbsp; &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"Tommy Au"<notifications@github.com&gt;; 发送时间:&nbsp;2019年12月30日(星期一) 中午1:44 收件人:&nbsp;"tommyau/itdseek"<itdseek@noreply.github.com&gt;; 抄送:&nbsp;"我是ydy"<1614999088@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题:&nbsp;Re: [tommyau/itdseek] Test my own samples (#7) ITDseek expects a bam file generated by BWA-MEM with -M option (as described in README at https://github.com/tommyau/itdseek). — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

ITDseek was developed for amplicon sequencing data. In principle (soft-clipping) it should also work with hybridization capture sequencing data to some extent.

**Comment by tommyau** [comment]
> Hi！ &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;I would also like to ask what principle the insertion mode mentioned in the source code（ line 83-108 in itdseek.pl） is based on to identify ITDs. &nbsp; &nbsp;&nbsp;Looking forward to your reply. Thank you！ &nbsp; &nbsp;&nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"我是ydy"<1614999088@qq.com&gt;; 发送时间:&nbsp;2019年12月31日(星期二) 上午10:20 收件人:&nbsp;"tommyau/itdseek"<reply@reply.github.com&gt;; 主题:&nbsp;回复： [tommyau/itdseek] Test my own samples (#7) Hi！ &nbsp; &nbsp; Thank you for your answer. &nbsp; &nbsp;May I ask whether the ITDseek is only suitable for amplicon sequencing data, and whether it is suitable for hkuozybridization sequencing data? &nbsp; &nbsp; &nbsp;
> ------------------ 原始邮件 ------------------ 发件人:&nbsp;"Tommy Au"<notifications@github.com&gt;; 发送时间:&nbsp;2019年12月30日(星期一) 中午1:44 收件人:&nbsp;"tommyau/itdseek"<itdseek@noreply.github.com&gt;; 抄送:&nbsp;"我是ydy"<1614999088@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题:&nbsp;Re: [tommyau/itdseek] Test my own samples (#7) ITDseek expects a bam file generated by BWA-MEM with -M option (as described in README at https://github.com/tommyau/itdseek). — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

In case there is ITD which is short enough and/or in the middle of amplicon, ITD will be present in BAM alignments in the form of insertions instead of soft-clipped. Insertion mode looks for these simple insertions in BAM alignments instead of soft-clipping. It is very similar to manually picking up insertions in BAM alignment viewer like IGV.
